//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_II_Milos_Peric
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalInstitutionDatabaseEntities : DbContext
    {
        public MedicalInstitutionDatabaseEntities()
            : base("name=MedicalInstitutionDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblClinicAdmin> tblClinicAdmins { get; set; }
        public virtual DbSet<tblClinicDoctor> tblClinicDoctors { get; set; }
        public virtual DbSet<tblClinicInstitution> tblClinicInstitutions { get; set; }
        public virtual DbSet<tblClinicMaintenace> tblClinicMaintenaces { get; set; }
        public virtual DbSet<tblClinicManager> tblClinicManagers { get; set; }
        public virtual DbSet<tblClinicPatient> tblClinicPatients { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<vwClinicAdmin> vwClinicAdmins { get; set; }
        public virtual DbSet<vwClinicDoctor> vwClinicDoctors { get; set; }
        public virtual DbSet<vwClinicMaintenance> vwClinicMaintenances { get; set; }
        public virtual DbSet<vwClinicManager> vwClinicManagers { get; set; }
        public virtual DbSet<vwClinicPatient> vwClinicPatients { get; set; }
    }
}
