//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_II_Milos_Peric
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClinicInstitution
    {
        public int InstitutionID { get; set; }
        public string InstitutionName { get; set; }
        public string CreationDate { get; set; }
        public string InstitutionOwner { get; set; }
        public string InstitutionAddress { get; set; }
        public Nullable<int> NumberOdFloors { get; set; }
        public Nullable<int> NumberOfRoomsPerFloor { get; set; }
        public Nullable<bool> HasTerrace { get; set; }
        public Nullable<bool> HasYard { get; set; }
        public Nullable<int> NumberOfAccessPointsForAmbulance { get; set; }
        public Nullable<int> NumberOfAccessPointsForInvalids { get; set; }
    }
}
